name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: fmcore/flagbrew_compiler
      credentials:
        username: ${{ secrets.DHU }}
        password: ${{ secrets.DHA }}

    steps:
      - name: "Clone"
        run: git clone --recurse-submodules -j8 https://github.com/FlagBrew/PKSM.git /PKSM
      - name: "Build"
        working-directory: "/PKSM"
        run: |
          make
          zip -r PKSM.zip 3ds/out/PKSM.cia 3ds/out/PKSM.3dsx 3ds/out/PKSM.elf
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: PKSBuild
          path: /PKSM
